import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Body, Head, Html, Node, themeScript } from '@meonode/ui'
import { StyleRegistry } from '@meonode/ui/nextjs-registry'
import { headers } from 'next/headers'
import { ReactNode } from 'react'
import { RootState } from '@src/redux/store'
import { Wrapper } from '@src/components/Wrapper'
import { themeConfig } from '@src/constants/themes/config'
import { userAgent } from 'next/server'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: ReactNode }) {
  const reqHeaders = await headers()
  const ua = userAgent({ headers: reqHeaders })
  const isMobile = ua.device.type === 'mobile' || ua.device.type === 'tablet'

  const preloadedState: RootState = {
    app: {
      isMobile,
    },
  }

  return Html({
    lang: 'en',
    /*
     * `data-theme` is deliberately absent. The server does not know which mode
     * the reader is in, and guessing is the flash this arrangement removes. The
     * script below writes it before the first paint; `suppressHydrationWarning`
     * is what stops React reporting the attribute it did not send.
     */
    suppressHydrationWarning: true,
    children: [
      /*
       * First in <head>, ahead of any stylesheet. A classic inline script placed
       * after a stylesheet cannot run until that sheet has loaded, which is the
       * delay this exists to avoid -- and `next/script` is no use either, since
       * even `beforeInteractive` is too late for this.
       */
      Head({
        key: 'theme',
        children: themeScript(themeConfig),
      }),
      Body({
        key: 'body',
        className: `${geistSans.variable} ${geistMono.variable} font-sans`,
        children: StyleRegistry({
          children: Node(Wrapper, {
            preloadedState,
            children,
          }),
        }),
      }),
    ],
  }).render()
}
